# Generated by Django 3.1.4 on 2020-12-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201207_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
