# Generated by Django 4.1.3 on 2022-12-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_app', '0002_remove_dostawca_ilosd_dostawca_ilosc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownicy',
            name='pesel',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
