# Generated by Django 4.1.3 on 2023-01-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catering_app', '0005_rename_naziwsko_pracownicy_nazwisko_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ('imie_klienta',)},
        ),
        migrations.AlterModelOptions(
            name='pracownicy',
            options={'ordering': ('imie',)},
        ),
        migrations.RemoveField(
            model_name='klient',
            name='do_zaplaty',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='zamowienie',
        ),
        migrations.AddField(
            model_name='klient',
            name='imie_klienta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='klient',
            name='nazwisko_klienta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='faktura',
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='klient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering_app.klient'),
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='posilki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catering_app.posilki'),
        ),
    ]
