# Generated by Django 4.1.3 on 2023-01-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_app', '0006_zamowienia_alter_klient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownicy',
            name='stanowisko',
            field=models.CharField(choices=[('kuc', 'kucharz'), ('kier', 'kierowca'), ('pom', 'pomocnik')], default='kier', max_length=5),
        ),
    ]
